version: "3"
services:
  hk-mysql: #서비스명
    container_name: hk-mysql
    restart: always # 꺼지면 자동으로 켜짐
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306" #3306으로 들어오면 내부 3306으로 때림 (포트포워딩)
    environment:
      MYSQL_DATABASE: cos
      MYSQL_ROOT_PASSWORD: bitc5600
      MYSQL_ROOT_HOST: "%" # 누구나 접근가능
    volumes: # 컴퓨터상의 볼륨
      #- ./db:/var/lib/mysql
      - db:/var/lib/mysql #insert, update 데이터 컨테이너 내려가면 다 날라감
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  backend:
    container_name: backend
    restart: always
    build: ./book-backend/.
    ports:
      - "8080:8080"
    depends_on: # hk-mysql 이 뜬후 뜸
      - hk-mysql

  frontend:
    container_name: frontend
    restart: always
    build: ./book-frontend/.
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend

volumes:
  db:
